frequency: 10
sensor_timeout: 0.2  
two_d_mode: true
      
publish_tf: true


odom_frame: odom
base_link_frame: base_link
world_frame: odom 
      
print_diagnostics: true

odom0: /robot_odom_wheels
odom1: /rtabmap/odom
imu0: /camera1/imu_filtered
imu1: /camera2/imu_filtered
      
odom0_nodelay: true 
imu0_nodelay: true 
imu1_nodelay: true 

#  X,        Y,      Z,
#  roll,     pitch,  yaw,
#  X/dt,     Y/dt,   Z/dt,
#  roll/dt,  pitch/dt,yaw/dt,
#  X/dt2,    Y/dt2,  Z/dt2 

odom0_config: [false, false, false, 
               false, false, false, 
               true,  true,  false, 
               false, false, true, 
               false, false, false]
                                      
odom1_config: [true,  true,  false, 
               false, false, true, 
               false, false, false,
               false, false, false, 
               false, false, false]

imu0_config: [false, false, false, 
              false, false, false,
              false, false, false, 
              false, true,  false,
              true,  false, true]

imu1_config: [false, false, false, 
              false, false, false,
              false, false, false, 
              false, true,  false,
              true,  false, true]

smooth_lagged_data:  false 
                                    
odom0_queue_size: 4
odom1_queue_size: 1
imu0_queue_size: 15
imu1_queue_size: 15

imu0_differential: false
imu1_differential: false

imu0_relative: true
imu1_relative: true
      
odom0_twist_rejection_threshold: 0.5
imu1_twist_rejection_threshold: 0.5
imu0_twist_rejection_threshold: 0.5
odom1_pose_rejection_threshold: 0.5
      
      
# process_noise_covariance: [LARGE ARRAY with small values] 
# initial_estimate_covariance: [LARGE ARRAY with 1e-9]
