TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.18
  min_vel_x: -0.18

  max_vel_theta:  0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.3

  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 1.0

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15

  holonomic_robot: true

# Forward Simulation Parameters
  sim_time: 3.0
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 30

# Trajectory Scoring Parameters
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true

  publish_cost_grid_pc: false

  oscillation_reset_dist: 0.08
  meter_scoring: true
