TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.18
  min_vel_x: 0.08

  max_vel_theta:  0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.6

  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 0.5

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.08
  yaw_goal_tolerance: 0.10


  holonomic_robot: true

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 3
  vtheta_samples: 20

  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true

  oscillation_reset_dist: 0.08
  meter_scoring: true
