TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.18
  min_vel_x: 0.08

  max_vel_theta:  0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.6

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.5

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05


  holonomic_robot: true


