footprint: [[ 0.378,  0.31], [-0.378,  0.31], [-0.378, -0.31], [ 0.378, -0.31]]
footprint_padding: 0.01

plugins:
   - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

inflation_layer:
  inflation_radius: 0.2 # 2xfootprint, it helps to keep the global planned path farther from obstacles
transform_tolerance: 1.0


