global_frame: odom
robot_base_frame: base_link
update_frequency: 1
publish_frequency: 4
rolling_window: true
width: 3.5
height: 3.5
resolution: 0.07
static_map: false
origin_x: 0
origin_y: 0

plugins:
  - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
  

obstacle_layer:
  obstacle_range: 3
  raytrace_range: 3.5
  max_obstacle_height: 0.4
  track_unknown_space: true

  observation_sources: point_cloud_sensor1_obstacle point_cloud_sensor2_obstacle
  
#  point_cloud_sensor1_ground: {
#    sensor_frame: camera1_link,
#    data_type: PointCloud2,
#    topic: ground_cloud_1,
#    expected_update_rate: 1.0,
#    marking: true,
#    clearing: true,
#    min_obstacle_height: 0.05
#  }

  point_cloud_sensor1_obstacle: {
    sensor_frame: camera1_link,
    data_type: PointCloud2,
    topic: obstacles_cloud_1,
    expected_update_rate: 1.0,
    marking: true,
    clearing: true,
    min_obstacle_height: -0.5 # make sure the ground is not filtered
  }
  
#  point_cloud_sensor2_ground: {
#    sensor_frame: camera2_link,
#    data_type: PointCloud2,
#    topic: ground_cloud_2,
#    expected_update_rate: 1.0,
#    marking: true,
#    clearing: true,
#    min_obstacle_height: 0.05
#  }

  point_cloud_sensor2_obstacle: {
    sensor_frame: camera2_link,
    data_type: PointCloud2,
    topic: obstacles_cloud_2,
    expected_update_rate: 1.0,
    marking: true,
    clearing: true,
    min_obstacle_height: -0.5 # make sure the ground is not filtered
  }
  
