global_frame: odom
robot_base_frame: base_link
update_frequency: 1
publish_frequency: 1
rolling_window: true
width: 4.5
height: 4.5
resolution: 0.05
static_map: false
origin_x: 0
origin_y: 0

plugins:
  - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}


inflation_layer:
  inflation_radius: 0.6 # 2xfootprint, it helps to keep the global planned path farther from obstacles


obstacle_layer:
  obstacle_range: 3
  raytrace_range: 10
  max_obstacle_height: 0.5
  min_obstacle_height: -0.5
  track_unknown_space: true

  observation_sources: point_cloud_sensor1_obstacle point_cloud_sensor2_obstacle

  point_cloud_sensor1_obstacle: {
    sensor_frame: camera1_link,
    data_type: LaserScan,
    topic: camera1/scan,
    expected_update_rate: 1.0,
    marking: true,
    clearing: true,
    inf_is_valid: true     #da usare con msg di tipo laser scan
  }

  point_cloud_sensor2_obstacle: {
    sensor_frame: camera2_link,
    data_type: LaserScan,
    topic: camera2/scan,
    expected_update_rate: 1.0,
    marking: true,
    clearing: true,
    inf_is_valid: true
  }
  
